# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Cerâmica é tudo!
email: 
description: > # this means to ignore newlines until "baseurl:"
  Sensibilizar crianças e adultos por meio de oficinas de argila  e divulgar a cerâmica por meio de palestras. Resgatar o passado e estimular o futuro na aplicação do material cerâmico, sempre com um olhar na arte atuando com os conceitos de sustentabilidade. Compartilhar a arte cerâmica, com informações de programas e eventos.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://lumizinski.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  

# Build settings
markdown: kramdown
